#Images (icons) for spells
import pygame

default = pygame.image.load("resources/img/items/default.png") #Useful default image that is also used for items
mend = pygame.image.load("resources/img/spells/mend.png")
heal = pygame.image.load("resources/img/spells/heal.png")
cure = pygame.image.load("resources/img/spells/cure.png")
icicle = pygame.image.load("resources/img/spells/icicle.png")
ice_spire = pygame.image.load("resources/img/spells/ice_spire.png")
mire = pygame.image.load("resources/img/spells/mire.png")
swell = pygame.image.load("resources/img/spells/swell.png")
large_swell = pygame.image.load("resources/img/spells/large_swell.png")
rogue_wave = pygame.image.load("resources/img/spells/rogue_wave.png")
tsunami = pygame.image.load("resources/img/spells/tsunami.png")
mist = pygame.image.load("resources/img/spells/mist.png")
aquablast = pygame.image.load("resources/img/spells/aquablast.png")
drizzle = pygame.image.load("resources/img/spells/drizzle.png")
rainstorm = pygame.image.load("resources/img/spells/rainstorm.png")
hail = pygame.image.load("resources/img/spells/hail.png")
deluge = pygame.image.load("resources/img/spells/deluge.png")
supersleet = pygame.image.load("resources/img/spells/supersleet.png")
breeze = pygame.image.load("resources/img/spells/breeze.png")
squall = pygame.image.load("resources/img/spells/squall.png")
gale = pygame.image.load("resources/img/spells/gale.png")
cyclone = pygame.image.load("resources/img/spells/cyclone.png")
waterspout = pygame.image.load("resources/img/spells/waterspout.png")
swab = pygame.image.load("resources/img/spells/swab.png")
batten = pygame.image.load("resources/img/spells/batten.png")
swig = pygame.image.load("resources/img/spells/swig.png")
lime = pygame.image.load("resources/img/spells/lime.png")
slime = pygame.image.load("resources/img/spells/slime.png")
revive = pygame.image.load("resources/img/spells/revive.png")
bestow = pygame.image.load("resources/img/spells/bestow.png")